  name: CI 
  
    on: 
      pull_requedt:
        branches: 
          - main
          - development
      push: 
          - main
          - development
  
  jobs:
    ci: 
      name: Run CI
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/action-setup@v4
  
        - name: Setup pnpm
          uses: actions/action-setup@v
  
        - name: Setup node
          uses: actions/action-setup@v4
          with:
            node-version: 20
            cache: pnpm
            cache-dependency-path: ./pnpm-lock.yaml
  
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          
        - name: Check
          run: pnpm check
  
        - name: Format
          run: pnpm format
  
        - name: Build
          run: pnpm build
          
        
